config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  devise_for :users
  resources :tokens
  resources :sanchaypatras do
    get "regenerate_tokens" => "sanchaypatras#regenerate_tokens"
    get "redeemable" => "sanchaypatras#redeemable", on: :collection
    get "expired" => "sanchaypatras#expired", on: :collection
  end

end

app/models/sanchaypatra.rb
class Sanchaypatra < ActiveRecord::Base
  belongs_to :user
  has_many :tokens

  scope :expired, -> { where(" expire_date < ?",Time.now) }
  scope :not_expired, -> { where(" expire_date >= ?",Time.now) }

  def generate_tokens
    redeem_dates = []
    redeem_months = ((self.active_date) .. self.expire_date).map{|d| [d.year, d.month]}.uniq
    redeem_months = redeem_months.drop(1)
    redeem_months.each do |year,month|
      if Date.valid_date?(year,month,self.active_date.day)
        redeem_dates << Date.new(year,month,self.active_date.day)
      else
        redeem_dates << Date.new(year,month,1).next_month
      end
    end
    associated_tokens = []
    redeem_dates = redeem_dates.every_nth(self.interval_month)
    redeem_dates.each_with_index do |date,index| # 1 day added to avoid the first date
      token = Token.new
      token.token_number = index+1
      token.token_date = date
      associated_tokens << token
    end
    self.tokens = associated_tokens
  end

end

app/controllers/sanchaypatras_controller.rb
class SanchaypatrasController < ApplicationController
  before_action :set_sanchaypatra, only: [:show, :edit, :update, :destroy, :regenerate_tokens]

  # GET /sanchaypatras
  # GET /sanchaypatras.json
  def index
    sanchaypatras =  current_user.sanchaypatras.not_expired
    sanchaypatras =  sanchaypatras.where("reg_number ilike ?","%#{params[:reg_number]}%") if params[:reg_number].present?
    sanchaypatras =  sanchaypatras.where("owner_name ilike ?","%#{params[:owner_name]}%") if params[:owner_name].present?
    @sanchaypatras_in_groups = sanchaypatras.order(:active_date).group_by(&:interval_month)
  end

  def expired
    sanchaypatras =  current_user.sanchaypatras.expired
    sanchaypatras =  sanchaypatras.where("reg_number ilike ?","%#{params[:reg_number]}%") if params[:reg_number].present?
    sanchaypatras =  sanchaypatras.where("owner_name ilike ?","%#{params[:owner_name]}%") if params[:owner_name].present?
    @sanchaypatras_in_groups = sanchaypatras.order(:active_date).group_by(&:interval_month)
  end

  # GET /sanchaypatras/1
  # GET /sanchaypatras/1.json
  def show
  end

  # GET /sanchaypatras/new
  def new
    @sanchaypatra = current_user.sanchaypatras.new
    @sanchaypatra.active_date = Time.now
    @sanchaypatra.expire_date = Time.now + 3.years
  end

  # GET /sanchaypatras/1/edit
  def edit
  end

  # POST /sanchaypatras
  # POST /sanchaypatras.json
  def create
    @sanchaypatra = current_user.sanchaypatras.new(sanchaypatra_params)
    @sanchaypatra.generate_tokens

    respond_to do |format|
      if @sanchaypatra.save
        format.html { redirect_to sanchaypatras_url, notice: 'Sanchaypatra was successfully created.' }
        format.json { render :show, status: :created, location: @sanchaypatra }
      else
        format.html { render :new }
        format.json { render json: @sanchaypatra.errors, status: :unprocessable_entity }
      end
    end
  end

  def regenerate_tokens
    @sanchaypatra.generate_tokens
    respond_to do |format|
      if @sanchaypatra.save
        format.html { redirect_to sanchaypatras_url, notice: 'Tokens was successfully regenerated.' }
        format.json { render :show, status: :created, location: @sanchaypatra }
      else
        format.html { render :new }
        format.json { render json: @sanchaypatra.errors, status: :unprocessable_entity }
      end
    end

  end

  # PATCH/PUT /sanchaypatras/1
  # PATCH/PUT /sanchaypatras/1.json
  def update
    respond_to do |format|
      if @sanchaypatra.update(sanchaypatra_params)
        format.html { redirect_to sanchaypatras_url, notice: 'Sanchaypatra was successfully updated.' }
        format.json { render :show, status: :ok, location: @sanchaypatra }
      else
        format.html { render :edit }
        format.json { render json: @sanchaypatra.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sanchaypatras/1
  # DELETE /sanchaypatras/1.json
  def destroy
    @sanchaypatra.destroy
    respond_to do |format|
      format.html { redirect_to sanchaypatras_url, notice: 'Sanchaypatra was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def redeemable
    @till_date = params["till_date(1i)"].present? ? Date.new(params["till_date(1i)"].to_i, params["till_date(2i)"].to_i, params["till_date(3i)"].to_i) : Time.now
    @sanchaypatras = current_user.sanchaypatras.includes(:tokens).where("tokens.is_redeemed = ? and tokens.token_date <= ?",false,@till_date).references(:tokens)
    @sanchaypatras =  @sanchaypatras.where("owner_name ilike ?","%#{params[:owner_name]}%") if params[:owner_name].present?
    @total_redeemable_amount = @sanchaypatras.collect{|s| s.tokens.length*s.profit_per_lac.to_f}.sum
    @sanchaypatras_in_groups = @sanchaypatras.order(:active_date).group_by(&:interval_month)
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_sanchaypatra
    @sanchaypatra = current_user.sanchaypatras.find(params[:id] || params[:sanchaypatra_id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def sanchaypatra_params
    #params.require(:sanchaypatra).permit(:reg_number, :issue_date, :amount, :profit_per_lac, :active_date, :expire_date, :profilt_percentage,:interval_month)
    params.require(:sanchaypatra).permit!
  end
end

app/helpers/sanchaypatras_helper.rb
module SanchaypatrasHelper
end

app/views/sanchaypatras/_form.html.erb
<%= form_for(@sanchaypatra) do |f| %>
  <% if @sanchaypatra.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sanchaypatra.errors.count, "error") %> prohibited this sanchaypatra from being saved:</h2>

      <ul>
      <% @sanchaypatra.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :reg_number %><br>
    <%= f.text_field :reg_number %>
  </div>
  <div class="form-group">
    <%= f.label :owner_name %><br>
    <%= f.text_field :owner_name %>
  </div>
  <div class="form-group">
    <%= f.label :nominee_name %><br>
    <%= f.text_field :nominee_name %>
  </div>
  <div class="form-group">
    <%= f.label :issue_date %><br>
    <%= f.date_select :issue_date %>
  </div>
  <div class="form-group">
    <%= f.label :amount %><br>
    <%= f.text_field :amount %>
  </div>
  <div class="form-group">
    <%= f.label :profit_per_lac, "Profit Per Interval" %><br>
    <%= f.text_field :profit_per_lac %>
  </div>
  <div class="form-group">
    <%= f.label :active_date %><br>
    <%= f.date_select :active_date %>
  </div>
  <div class="form-group">
    <%= f.label :expire_date %><br>
    <%= f.date_select :expire_date %>
  </div>
  <div class="form-group">
    <%= f.label :interval_month %><br>
    <%= f.text_field :interval_month %>
  </div>
  <div class="actions ">
    <%= f.submit :class => "btn btn-success" %>
    <%= link_to 'Cancel', sanchaypatras_path, :class => "btn btn-danger" %>
  </div>
<% end %>

app/views/sanchaypatras/_table.html.erb
<table class="table table-striped table-bordered" >
  <thead>
  <tr>
    <th>Reg number</th>
    <th>Owner</th>
    <th>Nominee</th>
    <th>Issue date</th>
    <th>Amount</th>
    <th>Profit per lac</th>
    <th>Active date</th>
    <th>Expire date</th>
    <th colspan="4">Actions</th>
  </tr>
  </thead>

  <tbody>
  <% sanchaypatras.each do |sanchaypatra| %>
    <tr>
      <td><%= sanchaypatra.reg_number %></td>
      <td><%= sanchaypatra.owner_name %></td>
      <td><%= sanchaypatra.nominee_name %></td>
      <td><%= sanchaypatra.issue_date %></td>
      <td><%= sanchaypatra.amount %></td>
      <td><%= sanchaypatra.profit_per_lac %></td>
      <td><%= sanchaypatra.active_date %></td>
      <td><%= sanchaypatra.expire_date %></td>
      <td><%= link_to 'Edit', edit_sanchaypatra_path(sanchaypatra) %></td>
      <td><%= link_to 'Destroy', sanchaypatra, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <td><%= link_to 'Tokens', tokens_path(:sanchaypatra_id => sanchaypatra.id) %></td>
      <td><%= link_to 'Regenerate Tokens', sanchaypatra_regenerate_tokens_path(:sanchaypatra_id => sanchaypatra.id), data: { confirm: 'Are you sure? This will delete all existing tokens and create new from scratch!!' } %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<br>

app/views/sanchaypatras/_table_with_tokens.html.erb
<table class="table table-striped table-bordered">
  <thead>
  <tr>
    <th>Reg number</th>
    <th>Owner</th>
    <th>Nominee</th>
    <th>Amount</th>
    <th>Profit per period</th>
    <th>Active date</th>
    <th>Expire date</th>
    <th colspan="4">Actions</th>
  </tr>
  </thead>

  <tbody>
  <% sanchaypatras.each do |sanchaypatra| %>
    <tr>
      <td><strong><%= sanchaypatra.reg_number %></strong></td>
      <td><%= sanchaypatra.owner_name %></td>
      <td><%= sanchaypatra.nominee_name %></td>
      <td class="align_right"><%= sanchaypatra.amount %></td>
      <td class="align_right"><%= sanchaypatra.profit_per_lac %></td>
      <td><%= sanchaypatra.active_date %></td>
      <td><%= sanchaypatra.expire_date %></td>
      <td><%= link_to 'Edit', edit_sanchaypatra_path(sanchaypatra) %></td>
      <td><%= link_to 'Destroy', sanchaypatra, method: :delete, data: {confirm: 'Are you sure?'} %></td>
      <td><%= link_to 'Tokens', tokens_path(:sanchaypatra_id => sanchaypatra.id) %></td>
      <td><%= link_to 'Regenerate Tokens', sanchaypatra_regenerate_tokens_path(:sanchaypatra_id => sanchaypatra.id), data: {confirm: 'Are you sure? This will delete all existing tokens and create new from scratch!!'} %></td>
    </tr>
    <% sanchaypatra.tokens.each do |token| %>
      <tr>
        <td> </td>
        <td colspan="3"> Token Number : <%= token.token_number %></td>
        <td class="align_right" ><%= token.sanchaypatra.profit_per_lac %></td>
        <td colspan="3"> Token Date : <%= token.token_date %></td>
        <td colspan="3">
          <% if token.is_redeemed? %>
              <img src='/tick.png'>
          <% else %>
              <%= check_box_tag 'is_redeemed', token.is_redeemed, token.is_redeemed, {:class => "is_redeemed", :token_id => token.id} %>
              <label>Reedem</label>
          <% end %>
        </td>
      </tr>
    <% end %>
    <tr style="background-color: #BBBBBB">
      <td> </td>
      <td colspan="3"> Total </td>
      <td class="align_right" ><strong><%= (sanchaypatra.profit_per_lac.to_f * sanchaypatra.tokens.length) %></strong></td>
      <td colspan="6"> </td>
    </tr>
  <% end %>
  </tbody>
</table>

<br>

app/views/sanchaypatras/edit.html.erb
<h1>Editing Sanchaypatra</h1>

<%= render 'form' %>

app/views/sanchaypatras/expired.html.erb
<div class="box-content total-amount-box">
  <% total_amount = current_user.sanchaypatras.expired.sum(:amount) %>
  <strong><%= total_amount %>  Tk.</strong>
</div>

<div class="box-content search-box">
  <%= form_for "", :url => expired_sanchaypatras_url, :method => "GET" do |f| %>
      <input type="text" class="form-control" style="width: 20%;display: inline-block" placeholder="Search By Reg Number" name="reg_number" id="srch-term" value="<%= params[:reg_number] %>">
      <input type="text" class="form-control" style="width: 20%;display: inline-block" placeholder="Search By Owner Name" name="owner_name" id="srch-term" value="<%= params[:owner_name] %>">
      <button type="submit" class="btn btn-primary">Search</button>
      <a class="btn btn-primary" href="/sanchaypatras/expired">Reset</a>
  <% end %>
</div>


<div class="box-content sanchaypatras-box">
  <% @sanchaypatras_in_groups.each do |interval, sanchaypatras| %>
      <h3>Interval Months : <%= interval %> </h3>
      <%= render :partial => "table", :locals => {:sanchaypatras => sanchaypatras.sort_by(&:active_date)} %>
      <br/>
  <% end %>
</div>

app/views/sanchaypatras/index.html.erb
<div class="box-content total-amount-box">
  <% total_amount = current_user.sanchaypatras.not_expired.sum(:amount) %>
  <strong><%= total_amount %>  Tk.</strong>
</div>

<div class="box-content search-box">
  <%= form_for "", :url => sanchaypatras_url, :method => "GET" do |f| %>
    <input type="text" class="form-control" style="width: 20%;display: inline-block" placeholder="Search By Reg Number" name="reg_number" id="srch-term" value="<%= params[:reg_number] %>">
    <input type="text" class="form-control" style="width: 20%;display: inline-block" placeholder="Search By Owner Name" name="owner_name" id="srch-term" value="<%= params[:owner_name] %>">
    <button type="submit" class="btn btn-primary">Search</button>
    <a class="btn btn-primary" href="/sanchaypatras/">Reset</a>
  <% end %>
</div>

<%= link_to 'New Sanchaypatra', new_sanchaypatra_path, :class => "btn btn-primary" %>

<div class="box-content sanchaypatras-box">
  <% @sanchaypatras_in_groups.each do |interval, sanchaypatras| %>
    <h3>Interval Months : <%= interval %> </h3>
    <%= render :partial => "table", :locals => {:sanchaypatras => sanchaypatras.sort_by(&:active_date)} %>
    <br/>
  <% end %>
</div>

app/views/sanchaypatras/new.html.erb
<h1>New Sanchaypatra</h1>

<%= render 'form' %>

app/views/sanchaypatras/redeemable.html.erb
<div class="box-content search-box">
  <%= form_for "", :url => redeemable_sanchaypatras_path, :method => "GET" do |f| %>
    Select Till Date : <%= f.date_select :till_date,{:default => (@till_date || Time.now)} %> &nbsp;&nbsp;| &nbsp; &nbsp;
      <input type="text" class="form-control" style="width: 20%;display: inline-block" placeholder="Search By Owner Name" name="owner_name" id="srch-term" value="<%= params[:owner_name] %>">
    <button type="submit" class="btn btn-primary">Search</button>
    <a class="btn btn-primary" href="/sanchaypatras/redeemable/">Reset</a>
  <% end %>
</div>

<div class="box-content sanchaypatras-box">
  <% @sanchaypatras_in_groups.each do |interval, sanchaypatras| %>
    <div class="panel-group">
      <div class="panel panel-default">
        <div class="panel-heading" data-toggle="collapse" href="#interval<%= interval %>" style="cursor:pointer;">
          <h4 class="panel-title">
            Interval <%= interval %> months (<%= total_profit_on_collection(sanchaypatras) %>)
          </h4>
        </div>
        <div id="interval<%= interval %>" class="panel-collapse collapse">
          <%= render :partial => "table_with_tokens", :locals => {:sanchaypatras => sanchaypatras.sort_by(&:active_date)} %>
          <br/>
        </div>
      </div>
    </div>
  <% end %>
  <h2>Total Redeemable Amount : <%= @total_redeemable_amount %></h2>
</div>

app/views/sanchaypatras/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Reg number:</strong>
  <%= @sanchaypatra.reg_number %>
</p>

<p>
  <strong>Issue date:</strong>
  <%= @sanchaypatra.issue_date %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @sanchaypatra.amount %>
</p>

<p>
  <strong>Profit per lac:</strong>
  <%= @sanchaypatra.profit_per_lac %>
</p>

<p>
  <strong>Active date:</strong>
  <%= @sanchaypatra.active_date %>
</p>

<p>
  <strong>Expire date:</strong>
  <%= @sanchaypatra.expire_date %>
</p>

<p>
  <strong>Profilt percentage:</strong>
  <%= @sanchaypatra.profilt_percentage %>
</p>

<%= link_to 'Edit', edit_sanchaypatra_path(@sanchaypatra) %> |
<%= link_to 'Back', sanchaypatras_path %>
<%= link_to 'Tokens', tokens_path(:sanchaypatra_id => @sanchaypatra.id) %>