config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  devise_for :users
  resources :tokens
  resources :sanchaypatras do
    get "regenerate_tokens" => "sanchaypatras#regenerate_tokens"
    get "redeemable" => "sanchaypatras#redeemable", on: :collection
    get "expired" => "sanchaypatras#expired", on: :collection
  end

end

app/models/token.rb
class Token < ActiveRecord::Base
  belongs_to :sanchaypatra

  scope :redeemed, -> { where(is_redeemed: true) }
  scope :not_redeemed, -> { where(is_redeemed: false) }
  scope :till_date, -> (to_date) { where("token_date <= ?",to_date) }



end

app/controllers/tokens_controller.rb
class TokensController < ApplicationController
  before_action :set_token, only: [:show, :edit, :update, :destroy]

  # GET /tokens
  # GET /tokens.json
  def index
    sanchaypatra = Sanchaypatra.find(params[:sanchaypatra_id])
    @tokens = sanchaypatra.tokens
    if params[:filter].present?
      if params[:filter][:redemption].present?
        @tokens = @tokens.where(:is_redeemed => true) if params[:filter][:redemption] == "redeemed"
        @tokens = @tokens.where(:is_redeemed => false) if params[:filter][:redemption] == "not_redeemed"
      end
      @tokens = @tokens.where("token_date <= ?", params[:filter][:till_date]) if params[:filter][:till_date].present?
    else
      @tokens
    end
    @tokens = @tokens.order(:token_number)
  end

  # GET /tokens/1
  # GET /tokens/1.json
  def show
  end

  # GET /tokens/new
  def new
    @token = Token.new
  end

  # GET /tokens/1/edit
  def edit
  end

  # POST /tokens
  # POST /tokens.json
  def create
    @token = Token.new(token_params)

    respond_to do |format|
      if @token.save
        format.html { redirect_to tokens_url(:sanchaypatra => @token.sanchaypatra), notice: 'Token was successfully created.' }
        format.json { render :show, status: :created, location: @token }
      else
        format.html { render :new }
        format.json { render json: @token.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tokens/1
  # PATCH/PUT /tokens/1.json
  def update
    respond_to do |format|
      if @token.update(token_params)
        format.html { redirect_to tokens_url(:sanchaypatra_id => @token.sanchaypatra_id), notice: 'Token was successfully updated.' }
        format.json { render :show, status: :ok, location: @token }
      else
        format.html { render :edit }
        format.json { render json: @token.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tokens/1
  # DELETE /tokens/1.json
  def destroy
    sanchaypatra = @token.sanchaypatra
    @token.destroy
    respond_to do |format|
      format.html { redirect_to tokens_url(:sanchaypatra => sanchaypatra), notice: 'Token was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_token
    @token = Token.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def token_params
    #params.require(:token).permit(:sanchaypatra_id, :token_number, :token_date, :is_redeemed)
    params.require(:token).permit!
  end
end

app/helpers/tokens_helper.rb
module TokensHelper
end

app/views/tokens/_form.html.erb
<%= form_for(@token) do |f| %>
  <% if @token.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@token.errors.count, "error") %> prohibited this token from being saved:</h2>

      <ul>
      <% @token.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :sanchaypatra_id %><br>
    <%= f.number_field :sanchaypatra_id %>
  </div>
  <div class="field">
    <%= f.label :token_number %><br>
    <%= f.number_field :token_number %>
  </div>
  <div class="field">
    <%= f.label :token_date %><br>
    <%= f.datetime_select :token_date %>
  </div>
  <div class="field">
    <%= f.label :is_redeemed %><br>
    <%= f.check_box :is_redeemed %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tokens/edit.html.erb
<h1>Editing Token</h1>

<%= render 'form' %>

<%= link_to 'Show', @token %> |
<%= link_to 'Back', tokens_path %>

app/views/tokens/index.html.erb
<div class="box-content search-box">
  <%= form_for "", :url => tokens_url(:sanchaypatra_id => params[:sanchaypatra_id]), :method => "GET" do |f| %>
    <div class="row">
      <div class="col-md-6 col-sm-12">
        <select class="form-control" onchange="this.form.submit();" name="filter[redemption]">
          <option value="">--Please Select--</option>
          <option <%= 'selected' if params[:filter] && params[:filter][:redemption] == "redeemed" %> value="redeemed">Redeemed</option>
          <option <%= 'selected' if params[:filter] && params[:filter][:redemption] == "not_redeemed" %> value="not_redeemed">Not
            Redeemed
          </option>
        </select>
      </div>
      <div class="col-md-6 col-sm-12">
        <div class='input-group date datepicker'>
          <input type='text' class="form-control" name="filter[till_date]" value="<%= params[:filter][:till_date] if params[:filter] && params[:filter][:till_date] %>"/>
            <span class="input-group-addon">
               <span class="glyphicon glyphicon-calendar"></span>
            </span>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-md-12" style="margin-top: 10px">
      <input type="hidden" value="<%= params[:sanchaypatra_id] %>" name="sanchaypatra_id">
      <button type="submit" class="btn btn-primary">Search</button>
      <a class="btn btn-primary" href="/tokens?sanchaypatra_id=<%=params[:sanchaypatra_id] %>">Reset</a>
      </div>
    </div>

  <% end %>
</div>

<div class="box-content tokens-box">

  <table class="table table-striped table-bordered">
    <thead>
    <tr>
      <th>Sanchaypatra</th>
      <th>Token number</th>
      <th>Token date</th>
      <th>Is redeemed</th>
      <th colspan="2">Actions</th>
    </tr>
    </thead>

    <tbody>
    <% @tokens.each do |token| %>
      <tr>
        <td><%= token.sanchaypatra.reg_number %></td>
        <td><%= token.token_number %></td>
        <td><%= token.token_date %></td>
        <td>
          <% if token.is_redeemed? %>
            <img src='/tick.png'>
          <% else %>
            <%= check_box_tag 'is_redeemed', token.is_redeemed, token.is_redeemed, {:class => "is_redeemed", :token_id => token.id} %>
          <% end %>

        </td>
        <td><%= link_to 'Edit', edit_token_path(token) %></td>
        <td><%= link_to 'Destroy', token, method: :delete, data: {confirm: 'Are you sure?'} %></td>
      </tr>
    <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to '<< Back', sanchaypatras_path %>
</div>

app/views/tokens/new.html.erb
<h1>New Token</h1>

<%= render 'form' %>

<%= link_to 'Back', tokens_path %>

app/views/tokens/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Sanchaypatra:</strong>
  <%= @token.sanchaypatra_id %>
</p>

<p>
  <strong>Token number:</strong>
  <%= @token.token_number %>
</p>

<p>
  <strong>Token date:</strong>
  <%= @token.token_date %>
</p>

<p>
  <strong>Is redeemed:</strong>
  <%= @token.is_redeemed %>
</p>

<%= link_to 'Edit', edit_token_path(@token) %> |
<%= link_to 'Back', tokens_path %>