config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  devise_for :users
  resources :tokens
  resources :sanchaypatras do
    get "regenerate_tokens" => "sanchaypatras#regenerate_tokens"
    get "redeemable" => "sanchaypatras#redeemable", on: :collection
    get "expired" => "sanchaypatras#expired", on: :collection
  end

end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Asset Management System</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <% if current_user.present? %>
          <li class="active">
            <a href="<%= sanchaypatras_path %>">Sanchaypatras <span class="sr-only">(current)</span></a></li>
          <li class="active">
            <a href="<%= redeemable_sanchaypatras_path %>">Reedemable? <span class="sr-only">(current)</span></a></li>
          <li class="active">
            <a href="<%= expired_sanchaypatras_path %>">Expired <span class="sr-only">(current)</span></a></li>
        <% end %>
        <!--<li><a href="/projects">Projects</a></li>-->
        <!--<li><a href="#">About US</a></li>-->
        <!--<li><a href="#">Contact US</a></li>-->
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li><%= link_to "Welcome <b>#{current_user.email}</b>".html_safe, '#' %></li>
          <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Sign In", new_user_session_path %></li>
          <li><%= link_to "Sign Up", new_user_registration_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_messages.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>">
    <a href="#" data-dismiss="alert" class="close">×</a>
    <ul>
      <li>
        <%= value %>
      </li>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Asset Management</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body style="background-color: #eaf4ff">

<div class="container" style="margin-bottom: 30px">
  <%= render 'layouts/header' %>
  <%= render 'layouts/messages' %>
  <%= yield %>
</div>


</body>
</html>